language: python
matrix:
  include:
    - python: '2.7'
      env: DOCKER_BUILD=1
      sudo: required
      dist: trusty
      services:
        - docker
    - python: '3.4'
    - python: '3.5'
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - coverage run $(which nosetests)
  - coverage xml && coverage report
  - flake8 .
  - if [ -n "$DOCKER_BUILD" ]; then docker build -t marathon-lb .; fi
  # Run some basic sanity checks...
  - if [ -n "$DOCKER_BUILD" ]; then docker run --rm --entrypoint haproxy marathon-lb -vv; fi
  - if [ -n "$DOCKER_BUILD" ]; then docker run --rm --entrypoint /marathon-lb/marathon_lb.py marathon-lb --help; fi
after_script:
  - if [ -n "$DOCKER_BUILD" ]; then docker images; fi

after_success:
  - codecov
